server:
  port: 8001
spring:
  application:
    name: orderserver
  cloud: # 使用nacos注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379


# 使用eureka注册中心
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/